In [2]:
import os
import csv
from Evtx.Evtx import Evtx
import xml.etree.ElementTree as ET
# function to convert EVTX file to CSV
def Convert_evtx_to_csv(file_name):
    write = file_name.split(".")[0]
    write = os.path.join("Small_suspious_logs", write+ ".csv")
    read = os.path.join("Small_suspious_logs",file_name)
    print(read)

    # defines the XML so that the column names can be found and data
    ns = {"e": "http://schemas.microsoft.com/win/2004/08/events/event"}
    # goes through and collects column names
    with Evtx(read) as log:
        field_names = set(["RecordNumber", "Timestamp", "EventID"])
    
        for record in log.records():
            xml_data = record.xml()
            root = ET.fromstring(xml_data)
            for data in root.findall(".//e:Data", ns):
                field_names.add(data.attrib.get("Name", "Unknown"))
    
        field_names = list(field_names)  
       # writes the data to csv using the column names that were found
        with open(write, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=field_names)
            writer.writeheader()
            with Evtx(read) as log2:
                for record in log2.records():
                    xml_data = record.xml()
                    root = ET.fromstring(xml_data)
                    
                    event = {
                        "RecordNumber": record.record_num(),
                        "Timestamp": root.find(".//e:TimeCreated", ns).attrib.get("SystemTime", ""),
                        "EventID": root.find(".//e:EventID", ns).text if root.find(".//e:EventID", ns) is not None else ""
                    }
    
                    for data in root.findall(".//e:Data", ns):
                        field = data.attrib.get("Name", "Unknown")
                        value = data.text if data.text else ""
                        event[field] = value
    
                    writer.writerow(event)
    
    print( write)

In [1]:
i = r"C:\Users\tcsim\Capstone_zip_files\Small_Normal_Data\small_normal.evtx"
# i = r"C:\Users\tcsim\Capstone_zip_files\Small_suspicious_logs\security_suspicious.evtx"
Convert_evtx_to_csv(i)

In [6]:
# "C:\Users\tcsim\Capstone_zip_files\Small_suspicious_logs\Security_Suspicious.csv"
# "C:\Users\tcsim\Capstone_zip_files\Small_Normal_Data\small_normal.csv"
import pandas as pd
df = pd.read_csv(r"C:\Users\tcsim\Capstone_zip_files\Small_suspicious_logs\Security_Suspicious.csv")
df

,ImpersonationLevel,ElevatedToken,SidHistory,CryptoAlgorithms,TestSigning,ClientProcessId,PrimaryGroupId,Workstation,TargetUserName,OldUacValue,...,SubStatus,SubjectDomainName,SchemaFriendlyName,ProcessName,LogonType,ProtectedDataFlags,TargetLinkedLogonId,ClassName,NewUacValue,Operation
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pizza,NaN,...,NaN,WORKGROUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,WORKGROUP,NaN,C:\Windows\System32\ctfmon.exe,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,...,NaN,DESKTOP-A3EGFSV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,pizza,NaN,...,NaN,DESKTOP-A3EGFSV,NaN,C:\Windows\System32\wevtutil.exe,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,...,NaN,WORKGROUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,...,NaN,WORKGROUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DESKTOP-A3EGFSV$,NaN,...,NaN,WORKGROUP,NaN,C:\Windows\WinSxS\amd64_microsoft-windows-serv...,NaN,NaN,NaN,NaN,NaN,NaN
5228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,WORKGROUP,NaN,C:\Windows\System32\Dism\DismHost.exe,NaN,NaN,NaN,NaN,NaN,NaN
5229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,WORKGROUP,NaN,C:\Windows\System32\directxdatabaseupdater.exe,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# import pandas as pd
# df = pd.read_csv(r"C:\Users\tcsim\PycharmProjects\Capstone-LLM-Project-\Small_Normal_Data\small_normal.csv")
# df
# df = pd.read_csv(r"C:\Users\tcsim\PycharmProjects\Capstone-LLM-Project-\Logs_Normal\security_normal.csv")

,LogonType,VirtualAccount,Resource,TargetProcessName,SidHistory,TargetName,TargetInfo,MasterKeyId,FailureReason,KeyType,...,LogonHours,ClassId,IpPort,ReturnCode,ClassName,KeyName,CommandLine,ProfilePath,LocationInformation,ConfigAccessPolicy
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,Registry,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,%%1846
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df = df.sort_values("Timestamp")

In [16]:
df

,TargetUserName,Timestamp,SubjectUserName,EventID,ParentProcessName,CommandLine,ProcessName,RowID
1,pizza,2026-04-20 18:00:18.158943+00:00,DESKTOP-A3EGFSV$,4688,C:\Windows\System32\svchost.exe,taskhostw.exe $(Arg0),NaN,1
2,NaN,2026-04-20 18:00:18.704304+00:00,DESKTOP-A3EGFSV$,4689,NaN,NaN,C:\Windows\System32\ctfmon.exe,2
3,-,2026-04-20 18:00:19.056101+00:00,pizza,4688,C:\Windows\System32\WindowsPowerShell\v1.0\pow...,"""C:\WINDOWS\system32\wevtutil.exe"" cl Security",NaN,3
4,pizza,2026-04-20 18:00:19.073996+00:00,pizza,4703,NaN,NaN,C:\Windows\System32\wevtutil.exe,4
5,pizza,2026-04-20 18:00:19.074104+00:00,pizza,4703,NaN,NaN,C:\Windows\System32\wevtutil.exe,5
...,...,...,...,...,...,...,...,...
5225,-,2026-04-20 18:26:30.742781+00:00,DESKTOP-A3EGFSV$,4688,C:\Windows\System32\services.exe,C:\WINDOWS\servicing\TrustedInstaller.exe,NaN,5225
5226,-,2026-04-20 18:26:30.789238+00:00,DESKTOP-A3EGFSV$,4688,C:\Windows\System32\svchost.exe,C:\WINDOWS\winsxs\amd64_microsoft-windows-serv...,NaN,5226
5227,DESKTOP-A3EGFSV$,2026-04-20 18:26:30.830265+00:00,DESKTOP-A3EGFSV$,4703,NaN,NaN,C:\Windows\WinSxS\amd64_microsoft-windows-serv...,5227
5228,NaN,2026-04-20 18:26:35.364809+00:00,DESKTOP-A3EGFSV$,4689,NaN,NaN,C:\Windows\System32\Dism\DismHost.exe,5228
5229,NaN,2026-04-20 18:26:35.374277+00:00,DESKTOP-A3EGFSV$,4689,NaN,NaN,C:\Windows\System32\directxdatabaseupdater.exe,5229

In [5]:

for i in df1.columns:
    print(i)

RemoteEventLogging
ResourceManager
TargetOutboundDomainName
CallerProcessName
VsmLaunchType
FlightSigning
AuthenticationPackageName
ForceLogoff
IpAddress
ProcessId
SchemaFriendlyName
TargetLinkedLogonId
KernelDebug
NewSd
AccessMask
MinPasswordLength
KeyFilePath
TargetUserSid
SubjectUserName
TargetUserName
HomeDirectory
TransactionId
LogonGuid
KeyName
TargetDomainName
Service
FileName
TargetServerName
KeyLength
HandleId
Workstation
LmPackageName
CommandLine
ClientCreationTime
LockoutThreshold
CategoryId
ReturnCode
MachineAccountQuota
OldUacValue
TargetLogonId
CallerProcessId
AllowedToDelegateTo
PasswordHistoryLength
KeyType
ConfigAccessPolicy
Type
ProviderName
UserAccountControl
UserWorkstations
Timestamp
PuaPolicyId
RestrictedAdminMode
LogonType
NewTime
PasswordProperties
PasswordLastSet
NewTargetUserName
TargetInfo
HypervisorLoadOptions
AccessRemoved
TargetOutboundUserName
ClientProcessStartKey
AlgorithmName
HypervisorLaunchType
AccessGranted
LockoutDuration
Flags
ElevatedToken
ImpersonationLevel
IpPort
RecordNumber
AccessList
PuaCount
ObjectType
ProcessName
DomainName
MaxPasswordAge
TargetName
SubjectLogonId
OldSd
SubcategoryGuid
SubjectDomainName
TargetProcessId
CountOfCredentialsReturned
Dummy
ObjectName
UserPrincipalName
MixedDomainMode
NewState
DisplayName
PrimaryGroupId
SubjectUserSid
Identity
AdvancedOptions
RemoteCredentialGuard
DomainSid
NewProcessName
OldTargetUserName
LinkName
PreviousTime
Schema
ProcessCreationTime
SidHistory
LoadOptions
AccountExpires
TestSigning
DomainPolicyChanged
EventID
UserParameters
OemInformation
DomainBehaviorVersion
ScriptPath
MandatoryLabel
ProfilePath
NewProcessId
MinPasswordAge
HomePath
PackageSid
ResourceAttributes
TokenElevationType
TargetSid
LogonHours
Resource
ClientProcessId
SubcategoryId
TargetProcessName
SamAccountName
MemberSid
PrivilegeList
LogonProcessName
TransmittedServices
NewUacValue
ObjectServer
ReadOperation
LockoutObservationWindow
ParentProcessName
WorkstationName
Operation
AuditPolicyChanges
MemberName
TargetLogonGuid
DisableIntegrityChecks
HypervisorDebug
VirtualAccount

In [11]:
df = pd.read_csv(r"C:\Users\tcsim\PycharmProjects\Capstone-LLM-Project-\Small_suspious_logs\security_suspicious.csv")
keepc = [  "EventID", "Timestamp", "SubjectUserName", "TargetUserName",  "ProcessName", "CommandLine", "ParentProcessName"]

# Keep only the columns in keepc that exist in the DataFrame
df = df[[col for col in df.columns if col in keepc]]

# drop columns with 0 values
df = df.dropna(axis=0, how='all')

# write to csv
df.to_csv(r"C:\Users\tcsim\PycharmProjects\Capstone-LLM-Project-\Small_suspious_logs\C_security_suspicious", index=False)

print("clean")

clean

In [10]:
df.to_csv(r"C:\Users\tcsim\PycharmProjects\Capstone-LLM-Project-\Small_Normal_Data\C_small_normal.csv", index=False)

In [12]:
import pandas as pd
df = pd.read_csv(r"C:\Users\tcsim\PycharmProjects\Capstone-LLM-Project-\Small_suspious_logs\C_security_suspicious")

In [20]:
# df = df.dropna(axis=1, how='all')

df["RowID"] = df.index

In [14]:
df

,TargetUserName,Timestamp,SubjectUserName,EventID,ParentProcessName,CommandLine,ProcessName,RowID
0,NaN,2026-04-20 18:00:19.082523+00:00,NaN,1102,NaN,NaN,NaN,0
1,pizza,2026-04-20 18:00:18.158943+00:00,DESKTOP-A3EGFSV$,4688,C:\Windows\System32\svchost.exe,taskhostw.exe $(Arg0),NaN,1
2,NaN,2026-04-20 18:00:18.704304+00:00,DESKTOP-A3EGFSV$,4689,NaN,NaN,C:\Windows\System32\ctfmon.exe,2
3,-,2026-04-20 18:00:19.056101+00:00,pizza,4688,C:\Windows\System32\WindowsPowerShell\v1.0\pow...,"""C:\WINDOWS\system32\wevtutil.exe"" cl Security",NaN,3
4,pizza,2026-04-20 18:00:19.073996+00:00,pizza,4703,NaN,NaN,C:\Windows\System32\wevtutil.exe,4
...,...,...,...,...,...,...,...,...
5225,-,2026-04-20 18:26:30.742781+00:00,DESKTOP-A3EGFSV$,4688,C:\Windows\System32\services.exe,C:\WINDOWS\servicing\TrustedInstaller.exe,NaN,5225
5226,-,2026-04-20 18:26:30.789238+00:00,DESKTOP-A3EGFSV$,4688,C:\Windows\System32\svchost.exe,C:\WINDOWS\winsxs\amd64_microsoft-windows-serv...,NaN,5226
5227,DESKTOP-A3EGFSV$,2026-04-20 18:26:30.830265+00:00,DESKTOP-A3EGFSV$,4703,NaN,NaN,C:\Windows\WinSxS\amd64_microsoft-windows-serv...,5227
5228,NaN,2026-04-20 18:26:35.364809+00:00,DESKTOP-A3EGFSV$,4689,NaN,NaN,C:\Windows\System32\Dism\DismHost.exe,5228
5229,NaN,2026-04-20 18:26:35.374277+00:00,DESKTOP-A3EGFSV$,4689,NaN,NaN,C:\Windows\System32\directxdatabaseupdater.exe,5229

In [17]:
# removing noise from the data
remove = [5379,5145, 5156, 5447, 4656, 4658, 4663, 4660, 4670, 4690, 4703, 4907, 5152, 5157]

for i in remove:
    df = df[df["EventID"] != i]
print("Done")

Done

In [1]:
# df["RowID"].drop(axis=0, inplace=True)

In [27]:
df.to_csv(r"C:\Users\tcsim\PycharmProjects\Capstone-LLM-Project-\Small_suspious_logs\C_security_suspicious", index=False)
# df.to_csv(r"C:\Users\tcsim\Capstone_zip_files\Small_Normal_Data\C_small_normal.csv", index=False)

In [43]:
df.columns

Index(['ProcessId', 'Timestamp', 'RecordNumber', 'ProcessName', 'EventID',
       'Reason'],
      dtype='str')

In [34]:
df.columns

Index(['EventID', 'RecordNumber', 'ErrorCode', 'Timestamp', 'User',
       'EventName', 'Reason', 'Operation', 'MessageText'],
      dtype='str')